#!/usr/bin/env npx tsx
/**
 * Generate a SQL migration that restores all 288 PT translations
 * from the original migration JSON data.
 *
 * Usage:
 *   npx tsx scripts/generate-translation-migration.ts > supabase/migrations/20260401400000_restore_pt_create_es_translations.sql
 */

import { readFileSync } from 'fs'
import { join } from 'path'

interface TranslationRow {
  id: string
  place_id: string
  locale: string
  name: string
  short_description: string | null
  full_description: string | null
}

const dataPath = join(__dirname, '..', 'data-migration', 'transformed', 'place_translations.json')
const raw: TranslationRow[] = JSON.parse(readFileSync(dataPath, 'utf-8'))
const ptRows = raw.filter(r => r.locale === 'pt')

function esc(v: string | null): string {
  if (v === null) return 'NULL'
  return `'${v.replace(/'/g, "''")}'`
}

const lines: string[] = []

lines.push(`-- ==========================================================`)
lines.push(`-- Restore PT translations from original migration data`)
lines.push(`-- Generated by scripts/generate-translation-migration.ts`)
lines.push(`-- ${new Date().toISOString()}`)
lines.push(`-- ==========================================================`)
lines.push(`-- 288 places: restores PT (locale='pt') translations.`)
lines.push(`-- Uses COALESCE(NULLIF(...,''), EXCLUDED...) so manually edited`)
lines.push(`-- translations are NOT overwritten — only NULL/empty fields`)
lines.push(`-- are restored from migration data.`)
lines.push(`-- ==========================================================`)
lines.push(``)
lines.push(`BEGIN;`)
lines.push(``)

for (const pt of ptRows) {
  lines.push(`-- ${pt.name}`)
  lines.push(`INSERT INTO place_translations (place_id, locale, name, short_description, full_description)`)
  lines.push(`VALUES (${esc(pt.place_id)}, 'pt', ${esc(pt.name)}, ${esc(pt.short_description)}, ${esc(pt.full_description)})`)
  lines.push(`ON CONFLICT (place_id, locale) DO UPDATE SET`)
  lines.push(`  name = CASE WHEN place_translations.translation_override IS TRUE THEN place_translations.name ELSE EXCLUDED.name END,`)
  lines.push(`  short_description = CASE WHEN place_translations.translation_override IS TRUE THEN place_translations.short_description ELSE EXCLUDED.short_description END,`)
  lines.push(`  full_description = CASE WHEN place_translations.translation_override IS TRUE THEN place_translations.full_description ELSE EXCLUDED.full_description END,`)
  lines.push(`  updated_at = now();`)
  lines.push(``)
}

lines.push(`COMMIT;`)
console.log(lines.join('\n'))