-- Expand place_translations.source CHECK to include 'llm_rewrite'.
-- 'llm_rewrite' marks rows regenerated by retranslate-all.ts (Claude Sonnet
-- 4.6 editorial pass) so editorial can filter them apart from human-curated
-- 'manual_fix' and raw 'manual' / 'deepl' / 'import' rows.
-- Idempotent.

BEGIN;

ALTER TABLE place_translations DROP CONSTRAINT IF EXISTS place_translations_source_check;

ALTER TABLE place_translations
  ADD CONSTRAINT place_translations_source_check
  CHECK (source IN ('manual','manual_fix','llm_rewrite','deepl','import'));

COMMIT;
