-- ============================================================================
-- Place Reservation Suggestions
-- Adds suggestion fields to places — separate from the active editorial config.
-- Suggestions are generated by heuristics or AI and serve as editorial aids.
-- The active config (booking_enabled, booking_mode, etc.) remains the source of truth.
-- ============================================================================

ALTER TABLE places
  ADD COLUMN suggestion_relevant       boolean,
  ADD COLUMN suggestion_mode           text,
  ADD COLUMN suggestion_label          text,
  ADD COLUMN suggestion_url            text,
  ADD COLUMN suggestion_confidence     numeric(3,2),
  ADD COLUMN suggestion_reason         text,
  ADD COLUMN suggestion_source         text,
  ADD COLUMN suggestion_generated_at   timestamptz,
  ADD COLUMN suggestion_dismissed      boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN places.suggestion_relevant     IS 'Suggested: whether this place is reservation-relevant';
COMMENT ON COLUMN places.suggestion_mode         IS 'Suggested booking mode (matches booking_mode enum values)';
COMMENT ON COLUMN places.suggestion_label        IS 'Suggested CTA label';
COMMENT ON COLUMN places.suggestion_url          IS 'Suggested booking URL';
COMMENT ON COLUMN places.suggestion_confidence   IS 'Confidence score 0.00–1.00 for the suggestion';
COMMENT ON COLUMN places.suggestion_reason       IS 'Why the suggestion was made (e.g. subcategory_match:restaurants)';
COMMENT ON COLUMN places.suggestion_source       IS 'Engine version that generated it (e.g. heuristic_v1)';
COMMENT ON COLUMN places.suggestion_generated_at IS 'When the suggestion was generated';
COMMENT ON COLUMN places.suggestion_dismissed    IS 'Editor dismissed this suggestion without applying';

-- Index for filtering places with pending suggestions
CREATE INDEX idx_places_has_suggestion
  ON places (suggestion_generated_at)
  WHERE suggestion_generated_at IS NOT NULL AND suggestion_dismissed = false;
